language: ruby
cache: bundler
sudo: false

rvm:
  - 2.1
  - 2.2
  - ruby-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: "ruby-head"

notifications:
  slack:
    secure: YA641QLW/evxS0VerCPI/EIEkW45QingXAwSH7tT6kycvxGi1ZH9cLV7imq5swtcCbyISGS3C14oMQHw8rzZLvc/TA2xnG+iv8kqQUMBr1UGlj8F9TniZGQT6XKHEvED/YP9IDaGBiiQpAtMLx/yISlnnIFfj4pTCCBfRERUgr4=

before_install:
  - gem i bundler -v 1.8.4

script:
  - '[ -e spec/environment/db/test.sqlite3 ] && rm spec/environment/db/test.sqlite3 || :'
  - bundle exec rspec -fd spec

