language: ruby
cache: bundler

rvm:
  - 2.1
  - 2.2
  - ruby-head

matrix:
  fast_finish: true
  allow_failures:
    - "ruby-head"

notifications:
  email:
    - travis-ci@sorah.jp

script:
  - '[ -e spec/environment/db/test.sqlite3 ] && rm spec/environment/db/test.sqlite3'
  - bundle exec rspec -fd spec

